server:
  port: 8099

#启动环境配置
spring:
  profiles:
    active: dev
  # thymelate配置
  thymeleaf:
    cache: true #enable templates cache
    check-template-location: false # check that the templates location exist
    content-type: text/html #Content-Type value
    enabled: true  # Enable MVC Thymeleaf view resolution
    encoding: UTF-8 #Template encoding
    mode: HTML5 # Template mode to be applied to templates. See also StandardTemplateModeHandlers
    suffix: .html
    prefix: classpath:/templates/

# 参数配置
com:
  wangheng:
    name: 王恒
    sex: 男
    desc: ${com.wangheng.name}是个大帅哥
    #随机字符串
    value: ${random.value}
